WITH DOSES AS (
	SELECT DISTINCT
		ENCNTR_ALIAS.ALIAS,
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.ORDER_ID,
		CASE 
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID		
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_ALIAS,
		ENCOUNTER,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37556132 -- amphotericin B liposomal
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -12), 'MONTH'), pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			-- 3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
), DOSE_COUNTS AS (
	SELECT
		ALIAS,
		ENCNTR_ID,
		ORIG_ORDER_ID,
		COUNT(DISTINCT EVENT_ID) AS NUM_DOSES
	FROM
		DOSES
	GROUP BY
		ALIAS,
		ENCNTR_ID,
		ORIG_ORDER_ID		
), ORD_DETAILS AS (
	SELECT DISTINCT
		ORDER_DETAIL.ORDER_ID,
		ORDER_DETAIL.OE_FIELD_MEANING,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE
	FROM
		DOSES,
		ORDER_DETAIL
	WHERE
		DOSES.ORIG_ORDER_ID = ORDER_DETAIL.ORDER_ID
		AND ORDER_DETAIL.ACTION_SEQUENCE = 1
), ORD_DETAIL_PIVOT AS (
	SELECT * FROM ORD_DETAILS
	PIVOT(
		MIN(OE_FIELD_DISPLAY_VALUE) FOR OE_FIELD_MEANING IN (

			'STRENGTHDOSE' AS DOSE,
			'STRENGTHDOSEUNIT' AS DOSE_UNIT,
			'WEIGHT' AS WEIGHT,
			'WEIGHTUNIT' AS WEIGHT_UNIT
		)
	)
)

SELECT
	DOSE_COUNTS.ALIAS AS FIN,
	DOSE_COUNTS.ORIG_ORDER_ID AS ORDER_ID,
	TO_NUMBER(ORD_DETAIL_PIVOT.DOSE) AS DOSE,
	ORD_DETAIL_PIVOT.DOSE_UNIT,
	TO_NUMBER(ORD_DETAIL_PIVOT.WEIGHT) AS WEIGHT,
	ORD_DETAIL_PIVOT.WEIGHT_UNIT,
	DOSE_COUNTS.NUM_DOSES
FROM
	DOSE_COUNTS,
	ORD_DETAIL_PIVOT
WHERE
	DOSE_COUNTS.ORIG_ORDER_ID = ORD_DETAIL_PIVOT.ORDER_ID(+)