WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS DOSE_MONTH,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.ORDER_ID,
		CASE 
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		CLINICAL_EVENT.EVENT_CD,
		LOWER(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.DOSAGE_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
		CE_MED_RESULT.ADMIN_ROUTE_CD,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ADMIN_ROUTE,
		CE_MED_RESULT.IV_EVENT_CD,
		pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		CASE
			WHEN pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) = 'HH STIC' THEN 'HH S STIC'
			WHEN pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) IN ('HH SIMU', 'HH S1MU') THEN 'HH S SIMU'
			WHEN pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) IN ('HH 6EJP', 'HH 6WJP') THEN 'HH S OTAC'
			WHEN pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) = 'HH 8NJP' THEN 'HH S SITU'
			WHEN pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) = 'HH 8WJP' THEN 'HH S BURN'
			ELSE pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD)
		END AS NURSE_UNIT_GROUPS
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557367 -- ketamine
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/2020 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'09/01/2020 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400,
				'America/Chicago'
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CE_MED_RESULT.IV_EVENT_CD IN (
			0,
			688706 -- Begin Bag
		)
		AND (CE_MED_RESULT.ADMIN_DOSAGE > 0 OR CE_MED_RESULT.INFUSION_RATE > 0)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			2369096643, -- HH TSCU
			3311213379 -- HH TICU
		)
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
), ACTIONS AS (
	SELECT
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORIG_ORDER_ID,
		MAX(ORDER_ACTION.ACTION_SEQUENCE) AS ACTION_SEQUENCE
	FROM
		DOSES,
		ORDER_ACTION
	WHERE
		DOSES.ORIG_ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_DT_TM < DOSES.EVENT_END_DT_TM
	GROUP BY
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORIG_ORDER_ID
), MED_PRODS AS (
	SELECT
		ACTIONS.ENCNTR_ID,
		ACTIONS.EVENT_ID,
		ACTIONS.ORIG_ORDER_ID,
		ACTIONS.ACTION_SEQUENCE,
		ORDER_PRODUCT.ITEM_ID,
		ORDER_PRODUCT.DOSE_QUANTITY,
		ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD,
		pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT
	FROM
		ACTIONS,
		ORDER_PRODUCT
	WHERE
		ACTIONS.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ACTIONS.ACTION_SEQUENCE = ORDER_PRODUCT.ACTION_SEQUENCE
		AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
), DOSES_PRODS AS (
	SELECT
		DOSES.*,
		MED_PRODS.ITEM_ID,
		MED_PRODS.DOSE_QUANTITY,
		MED_PRODS.DOSE_QUANTITY_UNIT_CD,
		MED_PRODS.DOSE_QUANTITY_UNIT,
		MED_IDENTIFIER.VALUE AS MED_PRODUCT	
	FROM
		DOSES,
		MED_IDENTIFIER,
		MED_PRODS
	WHERE
		DOSES.EVENT_ID = MED_PRODS.EVENT_ID(+)
		AND MED_PRODS.ITEM_ID = MED_IDENTIFIER.ITEM_ID(+)
		AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD(+) = 1564 -- Description
		AND MED_IDENTIFIER.MED_PRODUCT_ID(+) = 0
)

SELECT
	DOSE_MONTH,
	MEDICATION,
	MED_PRODUCT,
	COUNT(DISTINCT ENCNTR_ID) AS PATIENTS,
	COUNT(DISTINCT EVENT_ID) AS DOSES,
	SUM(DOSE_QUANTITY) AS QUANTITY
FROM
	DOSES_PRODS
WHERE
	MED_PRODUCT IS NOT NULL
GROUP BY
	DOSE_MONTH,
	MEDICATION,
	MED_PRODUCT