WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS DOSE_MONTH,
		CLINICAL_EVENT.EVENT_ID,
		LOWER(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)) AS MEDICATION,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		pi_get_cv_display(ENCNTR_LOC_HIST.MED_SERVICE_CD) AS MED_SERVICE,
		pi_get_cv_display(ENCNTR_LOC_HIST.ENCNTR_TYPE_CD) AS ENCNTR_TYPE,
		PRSNL.PERSON_ID,
		PRSNL.NAME_FULL_FORMATTED AS ATTENDING
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ENCNTR_PRSNL_RELTN,
		PRSNL
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557425 -- levothyroxine
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2018 00:00:00'}, User:1),
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				),
				pi_time_zone(1, 'America/Chicago')
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'06/01/2020 00:00:00'}, User:2),
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400,
				pi_time_zone(1, 'America/Chicago')
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND (
			(CE_MED_RESULT.ADMIN_DOSAGE > 0 AND CE_MED_RESULT.IV_EVENT_CD = 0)
			OR CE_MED_RESULT.IV_EVENT_CD = 688706 -- Begin Bag
		)
		AND CE_MED_RESULT.ADMIN_ROUTE_CD IN (
				508984, -- IV
				9022513, -- INJ
				9022647, -- IVPB
				9022649 -- IVP
		)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
		AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		AND ENCNTR_PRSNL_RELTN.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN ENCNTR_PRSNL_RELTN.BEG_EFFECTIVE_DT_TM AND ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM
		AND ENCNTR_PRSNL_RELTN.TRANSACTION_DT_TM = (
				SELECT MAX(EPR.TRANSACTION_DT_TM)
				FROM ENCNTR_PRSNL_RELTN EPR
				WHERE EPR.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND CLINICAL_EVENT.ENCNTR_ID = EPR.ENCNTR_ID
				AND EPR.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		)
		AND ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID = PRSNL.PERSON_ID
		AND PRSNL.PERSON_ID <> 59662830 -- Gift, Life MD
	)

SELECT * FROM DOSES