WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS MED_DATETIME,
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS MED_MONTH,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM 
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557691 -- norepinephrine
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
            pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter begin date', 'D', , mono, free, persistent, {'08/01/2022 00:00:00'}, User:0), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ), 
                pi_time_zone(1, 'America/Chicago')
            )
            AND pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter end date', 'D', , mono, free, persistent, {'02/01/2023 00:00:00'}, User:1), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ) - 1/86400, 
                pi_time_zone(1, 'America/Chicago')
            )	
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD = 688706 -- Begin Bag
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1   
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	DOSES.ENCNTR_ID,
	DOSES.MED_DATETIME,
	DOSES.MED_MONTH,
	DOSES.NURSE_UNIT,
	ORDER_PRODUCT.ITEM_ID,
	ORDER_PRODUCT.DOSE_QUANTITY,
	pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT,
	MED_IDENTIFIER.VALUE AS PRODUCT
FROM
	DOSES,
	ENCNTR_ALIAS,
	MED_IDENTIFIER,
	ORDER_PRODUCT
WHERE
	DOSES.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
	-- AND ORDER_PRODUCT.ACTION_SEQUENCE = 1
	-- AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Generic Name
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
	AND MED_IDENTIFIER.ITEM_ID = 2866373 -- norepinephrine 4 mg/4 ml inj
	AND DOSES.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
