WITH MED_ORDERS AS (
	SELECT DISTINCT
		ORDERS.ENCNTR_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		PERSON.NAME_FULL_FORMATTED AS PATIENT_NAME,
		ORDERS.ORDER_ID,
		pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
		-- pi_from_gmt(ORDERS.DISCONTINUE_EFFECTIVE_DT_TM, 'America/Chicago') AS ORDER_DISC_DATETIME,
		PRSNL.NAME_FULL_FORMATTED AS ORDER_PROVIDER,
		pi_get_cv_display(ORDERS.CATALOG_CD) AS MEDICATION,
		pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
		-- CASE WHEN ORDERS.PRN_IND = 1 THEN 'PRN' ELSE 'SCHEDULED' END AS PRN
	FROM
		ENCNTR_ALIAS,
		ENCNTR_DOMAIN,
		ENCOUNTER,
		ORDER_ACTION,
		ORDERS,
		PERSON,
		PRSNL
	WHERE
		ENCNTR_DOMAIN.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab
		) 
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.DISCH_DT_TM IS NULL
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			55851, -- Emergency
			688523 -- Observation
		)
		AND ENCOUNTER.PERSON_ID = ORDERS.PERSON_ID
		AND ENCOUNTER.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND ORDERS.CATALOG_CD = 3898755877 -- nirmatrelvir-ritonavir
		AND ORDERS.TEMPLATE_ORDER_ID = 0
		AND ORDERS.ORIG_ORD_AS_FLAG = 0
		AND ORDERS.ORDER_STATUS_CD = 1386 -- Ordered
		AND ORDERS.ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- ORDER
		AND ORDER_ACTION.ORDER_PROVIDER_ID = PRSNL.PERSON_ID
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND ENCOUNTER.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
), ORD_DETAILS AS (
	SELECT DISTINCT
		ORDER_DETAIL.ORDER_ID,
		-- ORDER_DETAIL.ACTION_SEQUENCE,
		MAX(ORDER_DETAIL.OE_FIELD_MEANING) KEEP (DENSE_RANK LAST ORDER BY ORDER_DETAIL.ACTION_SEQUENCE) OVER (PARTITION BY ORDER_DETAIL.ORDER_ID, ORDER_DETAIL.OE_FIELD_ID) AS OE_FIELD_MEANING,
		MAX(ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE) KEEP (DENSE_RANK LAST ORDER BY ORDER_DETAIL.ACTION_SEQUENCE) OVER (PARTITION BY ORDER_DETAIL.ORDER_ID, ORDER_DETAIL.OE_FIELD_ID) AS OE_FIELD_DISPLAY_VALUE
	FROM
		MED_ORDERS,
		ORDER_DETAIL
	WHERE
		MED_ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID
), ORD_DETAIL_PIVOT AS (
	SELECT * FROM ORD_DETAILS
	PIVOT(
		MIN(OE_FIELD_DISPLAY_VALUE) FOR OE_FIELD_MEANING IN (
			'STRENGTHDOSE' AS DOSE,
			'STRENGTHDOSEUNIT' AS DOSE_UNIT,
			'RXROUTE' AS ROUTE,
			'FREQ' AS FREQ,
			'DURATION' AS DURATION,
			'DURATIONUNIT' AS DURATION_UNIT,
			'STOPDTTM' AS STOP_DATETIME
		)
	)
), DOSES_PRODS AS (
	SELECT
		MED_ORDERS.ORDER_ID,
		ORDER_PRODUCT.ITEM_ID,
		-- ORDER_PRODUCT.DOSE_QUANTITY,
		-- pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT,
		MED_IDENTIFIER.VALUE AS PRODUCT_BRAND
	FROM
		MED_IDENTIFIER,
		MED_ORDERS,
		ORDER_PRODUCT
	WHERE
		MED_ORDERS.ORDER_ID = ORDER_PRODUCT.ORDER_ID(+)
		AND ORDER_PRODUCT.INGRED_SEQUENCE(+) = 1
		AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID(+)
		AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD(+) = 1562 -- Brand Name
		AND MED_IDENTIFIER.MED_PRODUCT_ID(+) = 0
)

SELECT 
	MED_ORDERS.*,
	DOSES_PRODS.PRODUCT_BRAND,
	ORD_DETAIL_PIVOT.DOSE,
	ORD_DETAIL_PIVOT.DOSE_UNIT,
	ORD_DETAIL_PIVOT.ROUTE,
	ORD_DETAIL_PIVOT.FREQ,
	ORD_DETAIL_PIVOT.DURATION,
	ORD_DETAIL_PIVOT.DURATION_UNIT,
	ORD_DETAIL_PIVOT.STOP_DATETIME
FROM 
	DOSES_PRODS,
	MED_ORDERS,
	ORD_DETAIL_PIVOT
WHERE
	MED_ORDERS.ORDER_ID = ORD_DETAIL_PIVOT.ORDER_ID
	AND MED_ORDERS.ORDER_ID = DOSES_PRODS.ORDER_ID(+)
	-- AND ORD_DETAIL_PIVOT.ROUTE IN ('IV', 'IVP', 'IVPB', 'INJ', 'IM', 'SUB-Q')
