WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		PERSON.NAME_FULL_FORMATTED AS NAME,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE AS DOSE,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSE_UNIT,
		PRSNL.NAME_FULL_FORMATTED AS ORDER_PROVIDER,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
		pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CD) AS ENCOUNTER_TYPE
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_ALIAS,
		ENCNTR_LOC_HIST,
		ENCOUNTER,
		ORDER_ACTION,
		ORDERS,
		PERSON,
		PRSNL
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557776 -- pegfilgrastim
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN 
			DECODE(
				@Prompt('Choose date range', 'A', {'Last Week', 'User-defined'}, mono, free, , , User:0),
				'Last Week', TRUNC(pi_to_gmt(SYSDATE - 7, 'America/Chicago'), 'DAY'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2020 00:00:00'}, User:1),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, 'America/Chicago')
				)
			)
			AND DECODE(
				@Prompt('Choose date range', 'A', {'Last Week', 'User-defined'}, mono, free, , , User:0),
				'Last Week', TRUNC(pi_to_gmt(SYSDATE, 'America/Chicago'), 'DAY') - 1/86400,
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'10/01/2020 00:00:00'}, User:2),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400,
					pi_time_zone(1, 'America/Chicago')
				)
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1   
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC
		)		
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND CLINICAL_EVENT.PERSON_ID = PERSON.PERSON_ID
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
		AND CLINICAL_EVENT.ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- Order
		AND ORDER_ACTION.ORDER_PROVIDER_ID = PRSNL.PERSON_ID 
)

SELECT DISTINCT
	DOSES.*,
	MED_IDENTIFIER.VALUE AS PRODUCT
FROM
	DOSES,
	MED_IDENTIFIER,
	ORDER_PRODUCT
WHERE
	DOSES.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
	-- AND ORDER_PRODUCT.ACTION_SEQUENCE = 1
	AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Generic Name
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
