WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'DAY') AS DOSE_WEEK,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		LOWER(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)) AS MEDICATION,
		CLINICAL_EVENT.ORDER_ID,
		/* CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.DOSAGE_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT, */
		CE_MED_RESULT.IV_EVENT_CD,
		pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
		ENCNTR_LOC_HIST.LOC_FACILITY_CD,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37557367, -- ketamine
			37556709, -- dexmedetomidine
			37556956, -- FENTanyl
			37557204, -- HYDROmorphone
			37557620, -- morphine Sulfate
			37557455, -- LORAzepam
			37557589, -- midazolam
			37557925 -- propofol
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(TRUNC(SYSDATE - 7*6, 'DAY'), pi_time_zone(2, @Variable('BOUSER')))
			-- pi_to_gmt(DATE '2020-01-05', pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD = 688706 -- Begin Bag
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			-- 3796, -- HC Childrens
			-- 3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			55851, -- Emergency
			688523 -- Observation
		)
), DISPENSED AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		DOSES.MEDICATION,
		MED_IDENTIFIER.VALUE AS MED_PRODUCT,
		DOSES.ORDER_ID,
		DISPENSE_HX.DISPENSE_HX_ID,
		DISPENSE_HX.DISPENSE_DT_TM,
		pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS DISPENSE_DATETIME,
		TRUNC(pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'DAY') AS DISPENSE_WEEK,
		DISPENSE_HX.DISP_EVENT_TYPE_CD,
		pi_get_cv_display(DISP_EVENT_TYPE_CD) AS DISP_EVENT_TYPE,
		DISPENSE_HX.DOSES,
		DISPENSE_HX.CHARGE_IND,
		CASE
			WHEN pi_get_cv_display(DISP_EVENT_TYPE_CD) IN ('Device Return', 'Manual Credit') THEN DISPENSE_HX.DOSES * DISPENSE_HX.CHARGE_IND * -1
			ELSE DISPENSE_HX.DOSES * DISPENSE_HX.CHARGE_IND
		END AS DISP_AMT
	FROM
		DISPENSE_HX,
		DOSES,
		MED_IDENTIFIER,
		ORDER_PRODUCT
	WHERE
		DOSES.ORDER_ID = DISPENSE_HX.ORDER_ID
		AND DISPENSE_HX.DISPENSE_DT_TM BETWEEN
			pi_to_gmt(TRUNC(SYSDATE - 7*6, 'DAY'), pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		AND DISPENSE_HX.ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND DISPENSE_HX.ACTION_SEQUENCE = ORDER_PRODUCT.ACTION_SEQUENCE
		AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
		AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Description
		AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
)

SELECT
	MEDICATION,
	MED_PRODUCT,
	DISPENSE_WEEK,
	SUM(DISP_AMT) AS DISP_AMT
FROM
	DISPENSED
GROUP BY
	MEDICATION,
	MED_PRODUCT,
	DISPENSE_WEEK


/* SELECT
	MEDICATION,
	MED_PRODUCT,
	FACILITY,
	NURSE_UNIT,
	DOSE_WEEK,
	COUNT(DISTINCT ENCNTR_ID) AS PATIENTS,
	COUNT(DISTINCT EVENT_ID) AS BAGS
FROM
	DOSES_PRODS
GROUP BY
	MEDICATION,
	MED_PRODUCT,
	FACILITY,
	NURSE_UNIT,
	DOSE_WEEK
 */