WITH NURSE_UNIT_PTS AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -18), 'America/Chicago')
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND ENCNTR_LOC_HIST.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), LABS_PREV_FY AS (
	SELECT
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS LAB_MONTH,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		COUNT(DISTINCT EVENT_ID) AS NUM_LABS
	FROM
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		NURSE_UNIT_PTS
	WHERE
		NURSE_UNIT_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND NURSE_UNIT_PTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			30724, -- Calcium Lvl
			522187789, -- Ca Ion WB
			32387, -- Magnesium Lvl
			33027 -- Phosphorus
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -18), 'America/Chicago')
			AND pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -6) - 1/86400, 'America/Chicago')
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
	GROUP BY
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH'),
		CLINICAL_EVENT.EVENT_CD
), UNIT_ENCNTR_LIST AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID
	FROM
		ENCNTR_LOC_HIST
	WHERE
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM BETWEEN
			pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -18), 'America/Chicago')
			AND pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -6) - 1/86400, 'America/Chicago')
), UNIT_TRNSFRS AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID AS ELH_ID,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		CASE
			WHEN 
				LAG(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN 1
			WHEN
				LEAD(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD
				AND LAG(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) = ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN -1
			ELSE 0
		END AS UNIT_TRANSFER,
		CASE
			WHEN 
				LAG(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN TRUNC(pi_from_gmt(ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM, 'America/Chicago'))
			WHEN
				LEAD(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD
				AND LAG(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) = ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN TRUNC(pi_from_gmt(ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM, 'America/Chicago'))
		END AS TRANSFER_DATE
	FROM
		ENCNTR_LOC_HIST,
		UNIT_ENCNTR_LIST
	WHERE
		UNIT_ENCNTR_LIST.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
), UNIT_TRNSFRS_DAILY AS (
	SELECT DISTINCT
		UNIT_TRNSFRS.TRANSFER_DATE,
		UNIT_TRNSFRS.LOC_NURSE_UNIT_CD,
		SUM(UNIT_TRNSFRS.UNIT_TRANSFER) AS NET_TRANSFERS
	FROM
		UNIT_TRNSFRS
	WHERE
		UNIT_TRNSFRS.UNIT_TRANSFER <> 0
		AND UNIT_TRNSFRS.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND UNIT_TRNSFRS.TRANSFER_DATE BETWEEN 
			pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -18), 'America/Chicago')
			AND pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -6) - 1/86400, 'America/Chicago')
	GROUP BY
		UNIT_TRNSFRS.TRANSFER_DATE,
		UNIT_TRNSFRS.LOC_NURSE_UNIT_CD
), CENSUS AS (
	SELECT DISTINCT
		TRUNC(pi_from_gmt(LH_CNT_LOC_UNIT_CENSUS.CENSUS_DT_TM, 'America/Chicago')) AS CENSUS_DATE,
		LH_CNT_LOC_UNIT_CENSUS.LOC_NURSE_UNIT_CD,
		LH_CNT_LOC_UNIT_CENSUS.CENSUS_PERSON_TOTAL AS CENSUS
	FROM
		LH_CNT_LOC_UNIT_CENSUS
	WHERE
		LH_CNT_LOC_UNIT_CENSUS.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND LH_CNT_LOC_UNIT_CENSUS.CENSUS_DT_TM BETWEEN
			pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -18), 'America/Chicago')
			AND pi_to_gmt(ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -6) - 1/86400, 'America/Chicago')
), PATIENT_DAYS AS (
	SELECT
		CENSUS.CENSUS_DATE,
		TRUNC(pi_from_gmt(CENSUS.CENSUS_DATE, 'America/Chicago'), 'MONTH') AS CENSUS_MONTH,
		CENSUS.LOC_NURSE_UNIT_CD,
		CENSUS.CENSUS,
		NVL(UNIT_TRNSFRS_DAILY.NET_TRANSFERS, 0) AS NET_TRANSFERS,
		CENSUS.CENSUS + NVL(UNIT_TRNSFRS_DAILY.NET_TRANSFERS, 0) AS PATIENT_DAYS
	FROM
		CENSUS,
		UNIT_TRNSFRS_DAILY
	WHERE 
		CENSUS.CENSUS_DATE = UNIT_TRNSFRS_DAILY.TRANSFER_DATE(+)
		AND CENSUS.LOC_NURSE_UNIT_CD = UNIT_TRNSFRS_DAILY.LOC_NURSE_UNIT_CD(+)
), PT_DAY_FY AS (
	SELECT
		CENSUS_MONTH,
		SUM(PATIENT_DAYS) AS PATIENT_DAYS
	FROM
		PATIENT_DAYS
	GROUP BY
		CENSUS_MONTH
)


SELECT
	LABS_PREV_FY.*,
	PT_DAY_FY.PATIENT_DAYS,
	LABS_PREV_FY.NUM_LABS / PT_DAY_FY.PATIENT_DAYS * 1000 AS LABS_THOUSAND_PT_DAYS
FROM
	LABS_PREV_FY,
	PT_DAY_FY
WHERE
	LABS_PREV_FY.LAB_MONTH = PT_DAY_FY.CENSUS_MONTH
