WITH ALL_MEDS AS (
	SELECT DISTINCT
		CODE_VALUE.CODE_VALUE AS EVENT_CD,
		CODE_VALUE.DISPLAY AS MEDICATION
	FROM
		CODE_VALUE
	WHERE
		CODE_VALUE.CODE_VALUE IN (
			-- 37556001, -- abciximab
			37556009, -- acetaminophen
			37556051, -- albumin human
			37556077, -- alteplase
			37556132, -- amphotericin B liposomal
			37556133, -- ampicillin
			37556134, -- ampicillin-sulbactam
			37556150, -- antihemophilic factor,
			37556449, -- cefazolin
			37556453, -- cefepime
			627676649, -- ceftaroline
			37556469, -- ceftriaxone
			37556587, -- coagulation factor VIIa
			37556681, -- daptomycin
			37556709, -- dexmedetomidine
			37556867, -- eptifibatide
			117038716, -- ertapenem
			37556889, -- esmolol
			37557233, -- immune globulin intravenous
			609787708, -- immune globulin intravenous and subcut
			37557425, -- levothyroxine
			37557527, -- meropenem
			37557578, -- METRONIDazole
			84261530, -- micafungin
			37557642, -- nafcillin
			37557675, -- niCARdipine
			37557681, -- nimodipine
			37557691, -- norepinephrine
			37557791, -- pentobarbital
			37557845, -- piperacillin-tazobactam
			37557925, -- propofol
			926562948, -- prothrombin complex
			37558315, -- vancomycin
			37558323 -- vasopressin
		) 
), ALL_MONTHS AS (
	SELECT 
		ADD_MONTHS(START_DATE, LEVEL-1) AS EVENT_MONTH
	FROM
		(
			SELECT 
				ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, 6), 'YEAR'), -@Prompt('Months Back', 'N', , mono, free, persistent, {'30'}, User:0)) START_DATE,
				TRUNC(SYSDATE, 'MONTH') END_DATE
			FROM
				DUAL
		)
	CONNECT BY LEVEL <= MONTHS_BETWEEN(TRUNC(END_DATE, 'MM'), TRUNC(START_DATE, 'MM'))
), ALL_UNITS AS (
	SELECT DISTINCT
		CODE_VALUE.CODE_VALUE AS LOC_NURSE_UNIT_CD,
		CODE_VALUE.DISPLAY AS NURSE_UNIT
	FROM
		CODE_VALUE
	WHERE
		CODE_VALUE.CODE_VALUE = 283905037 -- HH 7J
), START_MONTH AS (
	SELECT DISTINCT
		MIN(ALL_MONTHS.EVENT_MONTH) AS START_MONTH
	FROM
		ALL_MONTHS
), NURSE_UNIT_PTS AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID,
		ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM,
		ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM,
		ENCNTR_LOC_HIST.TRANSACTION_DT_TM,
		ENCNTR_LOC_HIST.LOC_FACILITY_CD,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM
	FROM
		ALL_UNITS,
		ENCNTR_LOC_HIST,
		ENCOUNTER,
		START_MONTH
	WHERE
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = ALL_UNITS.LOC_NURSE_UNIT_CD
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= pi_to_gmt(START_MONTH.START_MONTH, 'America/Chicago')
		-- AND ENCNTR_LOC_HIST.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCNTR_LOC_HIST.LOC_BUILDING_CD = 216053283 -- HH HVI
		AND ENCNTR_LOC_HIST.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), TARGET_MEDS AS (
	SELECT DISTINCT
		NURSE_UNIT_PTS.ENCNTR_ID,
		NURSE_UNIT_PTS.PERSON_ID,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		CLINICAL_EVENT.EVENT_END_DT_TM
	FROM
		ALL_MEDS,
		CE_MED_RESULT,
		CLINICAL_EVENT,
		NURSE_UNIT_PTS,
		START_MONTH
	WHERE
		NURSE_UNIT_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND CLINICAL_EVENT.EVENT_CD = ALL_MEDS.EVENT_CD
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(START_MONTH.START_MONTH, 'America/Chicago')
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, 'America/Chicago')
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND (
			CE_MED_RESULT.ADMIN_DOSAGE > 0 
			OR CE_MED_RESULT.IV_EVENT_CD = 688706 -- Begin Bag
		)
		AND (
			CLINICAL_EVENT.EVENT_CD NOT IN (
				37556009, -- acetaminophen
				37557425 -- levothyroxine
			) 
			OR CE_MED_RESULT.ADMIN_ROUTE_CD IN (
				508984, -- IV
				9022513, -- INJ
				9022647, -- IVPB
				9022649 -- IVP
			) 
		)
), DOSES AS (
	SELECT
		TARGET_MEDS.ENCNTR_ID AS ENCOUNTER_ID,
		TARGET_MEDS.EVENT_ID AS EVENT_ID,
		TRUNC(pi_from_gmt(TARGET_MEDS.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS EVENT_DATE,
		pi_get_cv_display(TARGET_MEDS.EVENT_CD) AS MEDICATION,
		pi_get_cv_display(NURSE_UNIT_PTS.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM 
		ALL_UNITS,
		NURSE_UNIT_PTS,
		TARGET_MEDS
	WHERE
		NURSE_UNIT_PTS.ENCNTR_ID = TARGET_MEDS.ENCNTR_ID
		AND NURSE_UNIT_PTS.PERSON_ID = TARGET_MEDS.PERSON_ID
		AND NURSE_UNIT_PTS.ENCNTR_LOC_HIST_ID = (
			SELECT MAX(NUP.ENCNTR_LOC_HIST_ID)
			FROM NURSE_UNIT_PTS NUP
			WHERE
				TARGET_MEDS.ENCNTR_ID = NUP.ENCNTR_ID
				AND NUP.TRANSACTION_DT_TM <= TARGET_MEDS.EVENT_END_DT_TM
				AND NUP.LOC_FACILITY_CD = 3310 -- HH HERMANN
				AND NUP.LOC_NURSE_UNIT_CD = ALL_UNITS.LOC_NURSE_UNIT_CD
				AND NUP.END_EFFECTIVE_DT_TM >= TARGET_MEDS.EVENT_END_DT_TM
		)
), DOSE_COUNTS AS (
	SELECT DISTINCT
		DOSES.NURSE_UNIT,
		DOSES.MEDICATION,
		DOSES.EVENT_DATE,
		COUNT(DISTINCT DOSES.EVENT_ID) AS NUM_DOSES
	FROM
		DOSES
	GROUP BY
		DOSES.NURSE_UNIT,
		DOSES.MEDICATION,
		DOSES.EVENT_DATE
), ALL_VALUES AS (
	SELECT *
	FROM 
		ALL_MEDS,
		ALL_MONTHS,
		ALL_UNITS
)

SELECT DISTINCT
	ALL_VALUES.NURSE_UNIT,
	ALL_VALUES.MEDICATION,
	ALL_VALUES.EVENT_MONTH,
	COALESCE(DOSE_COUNTS.NUM_DOSES, 0) AS NUM_DOSES
FROM
	ALL_VALUES,
	DOSE_COUNTS
WHERE
	ALL_VALUES.EVENT_MONTH = DOSE_COUNTS.EVENT_DATE(+)
	AND ALL_VALUES.MEDICATION = DOSE_COUNTS.MEDICATION(+)
	AND ALL_VALUES.NURSE_UNIT = DOSE_COUNTS.NURSE_UNIT(+)
 
