SELECT DISTINCT
	CLINICAL_EVENT.ENCNTR_ID,
	ENCNTR_ALIAS.ALIAS AS FIN,
	pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
	CLINICAL_EVENT.EVENT_ID,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	CE_MED_RESULT.ADMIN_DOSAGE,
	pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSE_UNIT,
	MED_IDENTIFIER.VALUE AS MED_PRODUCT
	-- MED_IDENTIFIER.ITEM_ID
	-- COUNT(DISTINCT CLINICAL_EVENT.EVENT_ID) AS NUM_DOSES
FROM
	CE_MED_RESULT,
	CLINICAL_EVENT,
	ENCNTR_ALIAS,
	ENCNTR_LOC_HIST,
	MED_IDENTIFIER,
	ORDERS,
	ORDER_PRODUCT
WHERE
	CLINICAL_EVENT.EVENT_CD = 37557995 -- rituximab
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
		pi_to_gmt(
			TO_DATE(
				@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2019 00:00:00'}, User:0), 
				pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
			), 
			'America/Chicago'
		)
		AND pi_to_gmt(
			TO_DATE(
				@Prompt('Enter end date', 'D', , mono, free, persistent, {'07/01/2020 00:00:00'}, User:1), 
				pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
			) - 1/86400,
			'America/Chicago'
		)
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
	AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
	AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
	AND CE_MED_RESULT.ADMIN_DOSAGE > 0
	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	)
	AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
		4501, -- HH 5EJP
		4601, -- HH 5WJP
		193270, -- HH STRK
		79976037, -- HH NIMU
		283905037, -- HH 7J
		2041371668 -- HH NVIC
	)
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
	AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
	AND CASE 
		WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID 
		ELSE ORDERS.TEMPLATE_ORDER_ID 
	END = ORDER_PRODUCT.ORDER_ID
	AND ORDER_PRODUCT.ACTION_SEQUENCE IN (1, 2)
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.ITEM_ID IN (
		5960935, -- Rituxan
		2805591, -- Rituxan
		293574779, -- Truxima
		300003295, -- Truxima
		302522233, -- Ruxience
		302522929 -- Ruxience
	)
	-- AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Description
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1562 -- Brand Name
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
/* GROUP BY
	ENCNTR_ALIAS.ALIAS,
	MED_IDENTIFIER.VALUE,
	TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH'),
	ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD
 */