WITH START_MONTH AS (
	SELECT DISTINCT
		DATE '2020-01-05' AS START_MONTH
	FROM
		DUAL
), ALL_CENSUS AS (
	SELECT 
		TRUNC(pi_from_gmt(LH_CNT_LOC_UNIT_CENSUS.CENSUS_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS CENSUS_DT_TM,
		LH_CNT_LOC_UNIT_CENSUS_ID,
		LOC_NURSE_UNIT_CD,
		pi_get_cv_display(LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		CENSUS_PERSON_TOTAL,
		LOC_FACILITY_CD,
		pi_get_cv_display(LOC_FACILITY_CD) AS FACILITY
	FROM 
		LH_CNT_LOC_UNIT_CENSUS,
		START_MONTH
	WHERE 
		LH_CNT_LOC_UNIT_CENSUS.CENSUS_DT_TM BETWEEN
			pi_to_gmt(START_MONTH.START_MONTH, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
), FACILITY_CENSUS AS (
	SELECT
		CENSUS_DT_TM,
		FACILITY,
		SUM(CENSUS_PERSON_TOTAL) AS CENSUS
	FROM 
		ALL_CENSUS
	WHERE
		FACILITY = 'HH HERMANN'
		AND NURSE_UNIT NOT IN ('HH PAHH', 'HH NNHH')
	GROUP BY
		CENSUS_DT_TM,
		FACILITY
), FACILITY_ADMITS AS (
	SELECT
		TRUNC(pi_from_gmt(REG_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS REG_DT_TM,
		COUNT(DISTINCT ENCNTR_ID) AS ADMITS
	FROM
		ENCOUNTER,
		START_MONTH
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN
			pi_to_gmt(START_MONTH.START_MONTH, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			-- 55851, -- Emergency
			688523 -- Observation
		)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
	GROUP BY
		TRUNC(pi_from_gmt(REG_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))))
), FACILITY_DISCH AS (
	SELECT
		TRUNC(pi_from_gmt(DISCH_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS DISCH_DT_TM,
		COUNT(DISTINCT ENCNTR_ID) AS DISCH
	FROM
		ENCOUNTER,
		START_MONTH
	WHERE
		ENCOUNTER.DISCH_DT_TM BETWEEN
			pi_to_gmt(START_MONTH.START_MONTH, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		AND ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			-- 55851, -- Emergency
			688523 -- Observation
		)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND TRUNC(ENCOUNTER.REG_DT_TM) <> TRUNC(ENCOUNTER.DISCH_DT_TM)
	GROUP BY
		TRUNC(pi_from_gmt(DISCH_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))))
)

SELECT
	CENSUS_DT_TM,
	CENSUS,
	ADMITS,
	DISCH,
	CENSUS + ADMITS - DISCH AS PT_DAYS
FROM
	FACILITY_ADMITS,
	FACILITY_CENSUS,
	FACILITY_DISCH
WHERE
	FACILITY_CENSUS.CENSUS_DT_TM = FACILITY_ADMITS.REG_DT_TM
	AND FACILITY_CENSUS.CENSUS_DT_TM = FACILITY_DISCH.DISCH_DT_TM
	