WITH NURSE_UNIT_PTS AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID,
		ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM,
		ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM,
		ENCNTR_LOC_HIST.TRANSACTION_DT_TM,
		ENCNTR_LOC_HIST.LOC_FACILITY_CD,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM
	FROM
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), pi_time_zone(2, @Variable('BOUSER')))
		AND ENCNTR_LOC_HIST.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		/* AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM BETWEEN
			pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, pi_time_zone(2, @Variable('BOUSER'))) */
), DOSES AS (
	SELECT DISTINCT
		NURSE_UNIT_PTS.ENCNTR_ID,
		NURSE_UNIT_PTS.PERSON_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS DOSE_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.ORDER_ID,
		CASE 
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		CLINICAL_EVENT.EVENT_CD,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.DOSAGE_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
		CE_MED_RESULT.ADMIN_ROUTE_CD,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ADMIN_ROUTE,
		CE_MED_RESULT.IV_EVENT_CD,
		pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		NURSE_UNIT_PTS,
		ORDERS
	WHERE
		NURSE_UNIT_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND CLINICAL_EVENT.EVENT_CD NOT IN (
			34239833, -- Administration Information
			37557975, -- remove patch
			94132365, -- nutritional supplemental
			37556835, -- empty container
			894195441 -- Overfill Diluent Estimated
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD IN (
			0,
			688706 -- Begin Bag
		)
		AND (CE_MED_RESULT.ADMIN_DOSAGE > 0 OR CE_MED_RESULT.INFUSION_RATE > 0)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
/* ), ACTIONS AS (
	SELECT
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORIG_ORDER_ID,
		MAX(ORDER_ACTION.ACTION_SEQUENCE) AS ACTION_SEQUENCE
	FROM
		DOSES,
		ORDER_ACTION
	WHERE
		DOSES.ORIG_ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_DT_TM < DOSES.EVENT_END_DT_TM
	GROUP BY
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORIG_ORDER_ID
), PROD_LOOKUP AS (
	SELECT
		ACTIONS.ENCNTR_ID,
		ACTIONS.EVENT_ID,
		ACTIONS.ORIG_ORDER_ID,
		ACTIONS.ACTION_SEQUENCE,
		ORDER_PRODUCT.ITEM_ID,
		ORDER_PRODUCT.DOSE_QUANTITY,
		ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD,
		pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT
	FROM
		ACTIONS,
		ORDER_PRODUCT
	WHERE
		ACTIONS.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ACTIONS.ACTION_SEQUENCE = ORDER_PRODUCT.ACTION_SEQUENCE
		AND ORDER_PRODUCT.INGRED_SEQUENCE = 1 */
), MED_PRODS AS (
	SELECT
		DOSES.ORIG_ORDER_ID,
		ORDER_PRODUCT.ITEM_ID,
		MIN(ORDER_PRODUCT.ACTION_SEQUENCE) AS ACTION_SEQUENCE,
		MIN(ORDER_PRODUCT.DOSE_QUANTITY) KEEP (DENSE_RANK FIRST ORDER BY ACTION_SEQUENCE) AS DOSE_QUANTITY,
		MIN(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) KEEP (DENSE_RANK FIRST ORDER BY ACTION_SEQUENCE) AS DOSE_QUANTITY_UNIT_CD
	FROM
		DOSES,
		ORDER_PRODUCT
	WHERE
		DOSES.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
		AND ORDER_PRODUCT.ITEM_ID NOT IN (
			5902104 -- sodium chloride SOLN
		)
	GROUP BY
		DOSES.ORIG_ORDER_ID,
		ORDER_PRODUCT.ITEM_ID
/* ), FIRST_ACTION AS (
	SELECT
		ORIG_ORDER_ID,
		MIN(ACTION_SEQUENCE) AS ACTION_SEQUENCE
	FROM MED_PRODS
	GROUP BY
		ORIG_ORDER_ID */
), NDC_LOOKUP AS (
	SELECT DISTINCT
		DOSES.ORIG_ORDER_ID,
		MIN(PHA_PROD_DISP_OBS_ST.MANF_NDC_STR) KEEP (DENSE_RANK FIRST ORDER BY PHA_PROD_DISP_OBS_ST.ACTION_SEQ) AS MANF_NDC_STR,
		MIN(SUBSTR(REGEXP_REPLACE(PHA_PROD_DISP_OBS_ST.MANF_NDC_STR, '-', ''), 1, 11)) KEEP (DENSE_RANK FIRST ORDER BY PHA_PROD_DISP_OBS_ST.ACTION_SEQ) AS NDC_CODE
	FROM
		DOSES,
		PHA_PROD_DISP_OBS_ST
	WHERE
		DOSES.ORIG_ORDER_ID = PHA_PROD_DISP_OBS_ST.ORDER_ID
		-- AND MED_PRODS.ACTION_SEQUENCE = PHA_PROD_DISP_OBS_ST.ACTION_SEQ
		AND PHA_PROD_DISP_OBS_ST.ING_SEQ = 1
	GROUP BY
		DOSES.ORIG_ORDER_ID
), PKG_NDC AS (
	SELECT
		DOSES.ORIG_ORDER_ID,
		COALESCE(MLTM_NDC_OUTER_INNER_MAP.OUTER_NDC_CODE, NDC_LOOKUP.NDC_CODE) AS PKG_NDC_CODE
	FROM
		DOSES,
		MLTM_NDC_OUTER_INNER_MAP,
		NDC_LOOKUP
	WHERE
		DOSES.ORIG_ORDER_ID = NDC_LOOKUP.ORIG_ORDER_ID(+)
		AND NDC_LOOKUP.NDC_CODE = MLTM_NDC_OUTER_INNER_MAP.INNER_NDC_CODE(+)	
), PKG_SIZE AS (
	SELECT
		PKG_NDC.ORIG_ORDER_ID,
		MLTM_NDC_CORE_DESCRIPTION.NDC_CODE,
		MLTM_NDC_CORE_DESCRIPTION.INNER_PACKAGE_SIZE,
		MLTM_NDC_CORE_DESCRIPTION.INNER_PACKAGE_DESC_CODE,
		MLTM_NDC_CORE_DESCRIPTION.OUTER_PACKAGE_SIZE,
		MLTM_NDC_COST.COST,
		MLTM_NDC_COST.INVENTORY_TYPE		
	FROM
		PKG_NDC,
		MLTM_NDC_CORE_DESCRIPTION,
		MLTM_NDC_COST
	WHERE
		PKG_NDC.PKG_NDC_CODE = MLTM_NDC_CORE_DESCRIPTION.NDC_CODE
		AND MLTM_NDC_CORE_DESCRIPTION.NDC_CODE = MLTM_NDC_COST.NDC_CODE
), COST_PIVOT AS (
	SELECT * FROM PKG_SIZE
	PIVOT(
		MIN(COST) FOR INVENTORY_TYPE IN (
			'A' AS A_COST,
			'C' AS C_COST,
			'F' AS F_COST,
			'M' AS M_COST,
			'W' AS W_COST
		)
	)
)

SELECT
	DOSES.*,
	-- MED_PRODS.ITEM_ID,
	MED_PRODS.DOSE_QUANTITY,
	pi_get_cv_display(MED_PRODS.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT,
	COST_PIVOT.NDC_CODE,
	COST_PIVOT.INNER_PACKAGE_SIZE,
	COST_PIVOT.INNER_PACKAGE_DESC_CODE,
	COST_PIVOT.OUTER_PACKAGE_SIZE,
	COST_PIVOT.A_COST,
	COST_PIVOT.C_COST,
	COST_PIVOT.F_COST,
	COST_PIVOT.M_COST,
	COST_PIVOT.W_COST
FROM
	COST_PIVOT,
	DOSES,
	MED_PRODS
WHERE
	DOSES.ORIG_ORDER_ID = COST_PIVOT.ORIG_ORDER_ID(+)
	AND DOSES.ORIG_ORDER_ID = MED_PRODS.ORIG_ORDER_ID
