SELECT DISTINCT
	TRUNC(pi_from_gmt(LH_CNT_LOC_UNIT_CENSUS.CENSUS_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS CENSUS_DATE,
	LH_CNT_LOC_UNIT_CENSUS.CENSUS_PERSON_TOTAL AS CENSUS
FROM
	LH_CNT_LOC_UNIT_CENSUS
WHERE
	LH_CNT_LOC_UNIT_CENSUS.LOC_NURSE_UNIT_CD = 5541 -- HH CVICU
	AND LH_CNT_LOC_UNIT_CENSUS.CENSUS_DT_TM
		BETWEEN pi_to_gmt(TRUNC(SYSDATE - 7, 'DAY'), pi_time_zone(2, @Variable('BOUSER')))
		AND pi_to_gmt(TRUNC(SYSDATE, 'DAY') - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
